#include <stdio.h>
#include <stdlib.h>

int main()
{
    int sayi;
    printf("Lutfen dizi buyuklugunu giriniz:");
    scanf("%d",&sayi);

    int dizi[sayi];

    /* BU GOSTERIM HATALIDIR.C DILI BIZDEN DIZIYI TANIMLARKEN BELIRLI BIR ALAN ISTER.YANI STATIK(SABIT BIR ALAN)ISTER.
       BIZ BURADA DIZI BOYUTUNU DEGISKENLE BELIRLEMIS OLDUK.YANI DINAMIK BIR ALAN TANIMLADIK.YAZILIMIN SONRAKI ADIMLARINDA
       BU DEGISKEN DEGISEBILIR.FARKLI BIR DEGER ALABILIR.AMA C DILI BUNU ISTEMEZ.
       */

    /* BU HATAYI GIDERMEK ICIN pointer VE malloc KULLANARAK DIZI TANIMLARIZ OLUR BITER.DEGISKEN DEGISSE DE SIKINTI OLMAZ.
    BELLEK BIZE YER VERIR.SONUCTA RANDOM ACCESS MEMORY IQ.
    */

    int *p =(int *)malloc(sizeof(int)*sayi);

    /* BU YAPTIGIMIZ P POINTERI TANIMIYLA.BELLEKTEN BOYUTU INTEGER OLAN,GIRILEN SAYI KADAR YER TALEP ETTIK.
    HATTA ILERIDE ARTABILIR VEYA AZALABILIR.SONUCTA DINAMIK ALAN.(***realloc***)
    MEMORYDE ACCESSLENDIK ORAYA.ERISIM VERILDI.POINTERIMIZ INT DONDUGU ICIN (MALLOC NORMALDE VOID)
    MALLOC'U INT'E CEVIRDIK. */

}
